### ISSUE TITLE
TinyMCE vs Redaktor

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [mirasvit/module-wysiwyg-editor#2]
TinyMCE sucks...
Redaktor rules!!!

Don't reinvent TinyMCE, better integrate Redaktor WYSIWYG

**Comment by adrok** [comment]
@devdesco-ceo https://imperavi.com/redactor/ -  not free anymore.

**Comment by devdesco-ceo** [comment]
1 - This one is superb: https://www.froala.com/wysiwyg-editor
2 - This one is simple with good UX: https://github.com/wysiwygjs/wysiwyg.js
3 - This one is good and feature rich: https://github.com/kindsoft/kindeditor
4 - Super simple one: https://github.com/summernote/summernote

Personally, I would go with 1 or 3.
All are free and open source.
